server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_service_02:3102/loki/api/v1/push  # Cambiado a 3102

scrape_configs:
  - job_name: demo_01_service_02
    static_configs:
      - targets:
          - localhost
        labels:
          job: demo_01_service_02
          __path__: /var/lib/docker/containers/*/*.log